language: node_js
node_js:
- '8'
services:
- docker
before_install:
- "./.travis/before-install.sh"
install:
- "./.travis/install.sh"
before_script:
- "./.travis/before-script.sh"
script:
- "./.travis/script.sh"
after_failure: tail -n +1 -- /home/travis/.npm/_logs/*-debug.log
sudo: required
env:
  global:
  - secure: wzbz7eCt7Ej+p378ii4UEDX7/GR0xHbj7HKuKP5J+uVBf/Gw29SUrO8MC5SnpE4gT9dLIZd6m/ibbVA56dtgILNkH+yfDjrmSm3ekb5LnFHrT4Gg35D8AHARdxnqh/4s3XNU3TEHoLfIHHwvXI99XzidKzv2Ldh3lmWCkYKLiieHzCsdfFJ2ZmzXrr8rm77Vb8fCCfsAvXxGZZdl/bcqfZ5iOo3QSYihtqy4myiYnmKX96Z+sjkUb7swPFKj/DFUfEv4kJH4D3eodIbDFM8DGf0W3OsorA6+hV6FEcrUjprmW/GOVz55sYTzjQiwE8aboD+gHKRxwHqh60/Q7RQMRzt6N2yUx/z/8G1xCHBPxErM8SVP664x8bcwrMfWKjWwv1J4uDO0YzdRPTRK9QjOwDArxbXzO9K1FL2lER6kmOMnMx9rWr+96JpDonl1SHmUKR19OHMSOY/+eVjhl8e5tSZQIuXlem2SVIn2M0Ua2gyHECSk52w+afUmtw6kibOjbyc2hT3T4SRAMZvGCjBWgYdm5jSsTiK3MX2CdobTbmsEWQxCAwUabR/udG4JWJ+m8IpbK3t4HCtzdYHcYbxCsUZVQuGP+HcnuUmwJvqjqqi1mJ7bFkJhMMeK0ojwfIn7LK3fsXYp5gtBYGG2vYLdPVLNng4ec4KnWPMjt1mQJF8=
  - secure: HK5Y45CZOA5AyUxkvfA8Wj7uooLUd0qzXK1eerx1qKtU8pVnQzphuhYdNdCJSKfywmH5f4hteJmLVHIX71ZifA7bY3w5rKtB1rUWNfqtWq/D4FCX4+NrFOce/mO3HSWTgFIp44+Cvj/EEx9M0uIYbMM3BMLlXbJl0w9ttKzkVsit79KZMUxH3jovjEQmdYfcLpCJA6RTgqT9VcfyHejnsF2iVAj0kAN4478+68uregTYB/VC9Hw6f97KUcYHp0y7fvCVr1wbsCwB0QG2VaEUrYt6DBWzfxQ/SC6ZMdMkdUf43Jd+ava6obVz6r2cp5o5yY6dQCNnHL+BT4tHgb2DnHjL//4GzdE7HUYxpjCp0WW6IUpce5cXDKsDys+qpVatR9nKq5pvRR9Jo5MlB1sMDIWiC+ehY8pBu24GOgfpU2/PO3RjjGpgpi6Nv59m9b6Ooks+rxOwMfAvcPG5SeFb5esrY9T77vtVEjfHz084VRuG9e0QUOHXyZ0a6vHN3BCmZ/i9Ruc24cL/AtUBOnZ0CTxbn1J4sNDjwKhzCL8h7Bm3qWi7mb+FFwErluH7pIIM6KDGGgzI0TDUTDbV3Q64irBAsK2UQYHeTz6hvTHXRSTckfCsVWnaGTE8LrNL9Hjo1L6UlmK4wlfSZ514mlTWdPddhi0EeWYiZJF0RagOUI8=
branches:
  only:
    - master
    - /([0-9]+\.){2}[0-9]+/
